sudo: false
cache:
  directories:
  - $HOME/.m2
language: java
jdk:
  - openjdk8
 
env:
  global:
    - SONATYPE_USERNAME=chicchiricco
    - secure: "x819XbM+j3eiERI6BMWnN8/DS7DQ1iDw7aPvMEMbUFvn0Cbn7TeqcgKUKld6cAoFMwA5KHZYxqHMKm35pj2JwIm/GWzCyZcSuZKFWuyOD1spxuC3W+33Cy29xVDKRisFJnD7ARCS6fDq3oWRJ5EuI2YUloCaEIl7Z764rEkv23E="
    - secure: "iIsgC6scB4VzftQyvrjLkjyGhRC4HsPeFKjgwa1144tEcK12E/GSJdCMPEeS9ihfT1lQssbUTOV4uXK2WlKRqi3Wi5bslkJfWCY4B8mRxTUYoKwNNHOn5f/tdTkjAm0UoTWx6u9hU3HupIuGkDs75K30vTxsRU1kJqeEilmxzl0="

before_install:
  - cd java

after_success:
  - python ../.travis.addServer.py
  - mvn clean deploy --settings ~/.m2/mySettings.xml

notifications:
  email:
    - connid-dev@googlegroups.com

addons:
  coverity_scan:
    project:
      name: "Tirasa/ConnId"
      description: "Build submitted via Travis CI"
    notification_email: connid-dev@googlegroups.com
    build_command_prepend: "mvn clean"
    build_command:   "mvn install"
    branch_pattern: master
