language: java
 
env:
  global:
    - SONATYPE_USERNAME=chicchiricco
    - secure: "x819XbM+j3eiERI6BMWnN8/DS7DQ1iDw7aPvMEMbUFvn0Cbn7TeqcgKUKld6cAoFMwA5KHZYxqHMKm35pj2JwIm/GWzCyZcSuZKFWuyOD1spxuC3W+33Cy29xVDKRisFJnD7ARCS6fDq3oWRJ5EuI2YUloCaEIl7Z764rEkv23E="

before_install:
  - cd java

after_success:
  - python ../.travis.addServer.py
  - mvn clean deploy --settings ~/.m2/mySettings.xml

notifications:
  email:
    - connid-dev@googlegroups.com
